spring:
  data:
    mongodb:
      host: "${MONGO_HOST:localhost}"
      port: ${MONGO_PORT:27017}
      database: "${MONGO_DATABASE:adversea_search}"
      authentication-database: admin
      username: "${MONGO_USERNAME:root}"
      password: "${MONGO_PASSWORD:example}"