openapi: 3.0.0
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/dominik-horvath/search-service/1.0.0
info:
  description: This is a simple API for adversea search service
  version: "1.0.0"
  title: search service
paths:
  /search:
    get:
      summary: Search for a person in adversea system
      operationId: searchName
      parameters:
        - name: name
          in: query
          required: true
          description: The name to search
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchResult'

  /sources:
    get:
      summary: Get source materials for an entity based on it's ID
      operationId: getSources
      parameters:
        - name: entityId
          in: query
          required: true
          description: ID of an entity you want to retrieve sources
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SourcesResult'
        '404':
          description: Not found
components:
  schemas:
    SourcesResult:
      type: object
      properties:
        ams:
          type: array
          items:
            type: string
            example: "https://aktuality.sk/kocner"
        pep:
          type: array
          items:
            type: string
            example: "tpod87d5ga8whnj78"

        sl:
          type: array
          items:
            type: string
            example: "t98hr64f65d4g8"

    SearchResult:
      type: array
      items:
        $ref: '#/components/schemas/SearchEntityResponse'
    SearchEntityResponse:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        name_ascii:
          type: string
        type:
          type: string
          enum:
            - person
            - organization
        locations:
          type: array
          items:
            type: string
        source:
          type: array
          items:
            type: string